
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import StringVar, Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter.ttk import Combobox, OptionMenu, Style
from typing import Any


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\MARKETING SUPPORT\Documents\asteros\astrs_work\special_\result\app_so\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

session_combobox = None

def main_UI():
    window = Tk()

    window.geometry("901x582")
    window.configure(bg = "#CDCDCA")


    canvas = Canvas(
        window,
        bg = "#CDCDCA",
        height = 582,
        width = 901,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        40.0,
        43.0,
        anchor="nw",
        text="Upload file",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=398.0,
        y=55.0,
        width=89.0,
        height=51.0
    )



    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=28.0,
        y=393.0,
        width=140.0,
        height=38.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=540.0,
        y=503.0,
        width=140.0,
        height=38.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=721.0,
        y=502.0,
        width=140.0,
        height=38.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_6 clicked"),
        relief="flat"
    )
    button_6.place(
        x=189.0,
        y=393.0,
        width=140.0,
        height=38.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_7 clicked"),
        relief="flat"
    )
    button_7.place(
        x=350.0,
        y=393.0,
        width=140.0,
        height=38.0
    )

    button_image_8 = PhotoImage(
        file=relative_to_assets("button_8.png"))
    button_8 = Button(
        image=button_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_8 clicked"),
        relief="flat"
    )
    button_8.place(
        x=722.0,
        y=442.0,
        width=140.0,
        height=38.0
    )

    button_image_9 = PhotoImage(
        file=relative_to_assets("button_9.png"))
    button_9 = Button(
        image=button_image_9,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_9 clicked"),
        relief="flat"
    )
    button_9.place(
        x=722.0,
        y=340.0,
        width=140.0,
        height=38.0
    )

    button_image_10 = PhotoImage(
        file=relative_to_assets("button_10.png"))
    button_10 = Button(
        image=button_image_10,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_10 clicked"),
        relief="flat"
    )
    button_10.place(
        x=540.0,
        y=442.0,
        width=140.0,
        height=38.0
    )

    button_image_11 = PhotoImage(
        file=relative_to_assets("button_11.png"))
    button_11 = Button(
        image=button_image_11,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_11 clicked"),
        relief="flat"
    )
    button_11.place(
        x=540.0,
        y=340.0,
        width=140.0,
        height=38.0
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        835.0,
        69.0,
        image=image_image_1
    )

    canvas.create_text(
        800.0,
        96.0,
        anchor="nw",
        text="Maker : Ben",
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        421.5,
        162.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=372.0,
        y=145.0,
        width=99.0,
        height=33.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        421.5,
        223.5,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=372.0,
        y=206.0,
        width=99.0,
        height=33.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        421.5,
        291.5,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=372.0,
        y=274.0,
        width=99.0,
        height=33.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        291.0,
        359.5,
        image=entry_image_4
    )
    entry_4 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=269.0,
        y=342.0,
        width=44.0,
        height=33.0
    )

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        411.0,
        359.5,
        image=entry_image_5
    )
    entry_5 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_5.place(
        x=389.0,
        y=342.0,
        width=44.0,
        height=33.0
    )

    button_image_12 = PhotoImage(
        file=relative_to_assets("button_12.png"))
    button_12 = Button(
        image=button_image_12,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_12 clicked"),
        relief="flat"
    )
    button_12.place(
        x=200.0,
        y=240.0,
        width=100.0,
        height=26.0
    )

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        204.0,
        82.5,
        image=entry_image_6
    )
    entry_6 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_6.place(
        x=36.0,
        y=65.0,
        width=336.0,
        height=33.0
    )

    entry_image_7 = PhotoImage(
        file=relative_to_assets("entry_7.png"))
    entry_bg_7 = canvas.create_image(
        129.0,
        359.5,
        image=entry_image_7
    )
    entry_7 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_7.place(
        x=32.0,
        y=342.0,
        width=194.0,
        height=33.0
    )

    entry_image_8 = PhotoImage(
        file=relative_to_assets("entry_8.png"))
    entry_bg_8 = canvas.create_image(
        258.5,
        520.5,
        image=entry_image_8
    )
    entry_8 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_8.place(
        x=25.0,
        y=481.0,
        width=467.0,
        height=77.0
    )

    canvas.create_rectangle(
        28.99999976134464,
        130.0,
        30.00000762939453,
        311.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        149.00000739073917,
        130.0,
        150.00001525878906,
        311.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        349.9999921319501,
        130.0,
        351.0,
        311.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        490.9999921319501,
        130.0,
        492.0,
        311.0,
        fill="#000000",
        outline="")

    entry_image_9 = PhotoImage(
        file=relative_to_assets("entry_9.png"))
    entry_bg_9 = canvas.create_image(
        250.5,
        181.5,
        image=entry_image_9
    )
    entry_9 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_9.place(
        x=179.0,
        y=164.0,
        width=143.0,
        height=33.0
    )

    canvas.create_text(
        65.00000762939453,
        127.0,
        anchor="nw",
        text="SESSION",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    canvas.create_text(
        32.0,
        324.0,
        anchor="nw",
        text="Keterangan :",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    canvas.create_text(
        217.00001525878906,
        127.0,
        anchor="nw",
        text="LOCATION",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    canvas.create_text(
        372.0,
        127.0,
        anchor="nw",
        text="SKU :",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    button_image_13 = PhotoImage(
        file=relative_to_assets("button_13.png"))
    button_13 = Button(
        image=button_image_13,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_13 clicked"),
        relief="flat"
    )
    button_13.place(
        x=438.0,
        y=449.0,
        width=46.0,
        height=23.0
    )



    canvas.create_text(
        372.0,
        188.0,
        anchor="nw",
        text="Quantity :",
        fill="#000000",
        font=("Inter Bold", 12 * -1)
    )

    canvas.create_text(
        372.0,
        258.0,
        anchor="nw",
        text="Qty tambahan :",
        fill="#000000",
        font=("Inter Bold", 10 * -1)
    )

    canvas.create_text(
        271.0,
        329.0,
        anchor="nw",
        text="Koli:",
        fill="#000000",
        font=("Inter Bold", 8 * -1)
    )

    canvas.create_text(
        391.0,
        329.0,
        anchor="nw",
        text="Koli:",
        fill="#000000",
        font=("Inter Bold", 8 * -1)
    )

    entry_image_10 = PhotoImage(
        file=relative_to_assets("entry_10.png"))
    entry_bg_10 = canvas.create_image(
        345.0,
        359.5,
        image=entry_image_10
    )
    entry_10 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_10.place(
        x=323.0,
        y=342.0,
        width=44.0,
        height=33.0
    )

    entry_image_11 = PhotoImage(
        file=relative_to_assets("entry_11.png"))
    entry_bg_11 = canvas.create_image(
        465.0,
        359.5,
        image=entry_image_11
    )
    entry_11 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_11.place(
        x=443.0,
        y=342.0,
        width=44.0,
        height=33.0
    )

    entry_image_12 = PhotoImage(
        file=relative_to_assets("entry_12.png"))
    entry_bg_12 = canvas.create_image(
        670.0,
        162.5,
        image=entry_image_12
    )
    entry_12 = Entry(
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    entry_12.place(
        x=570.0,
        y=145.0,
        width=200.0,
        height=33.0
    )

    canvas.create_text(
        327.0,
        329.0,
        anchor="nw",
        text="isi:",
        fill="#000000",
        font=("Inter Bold", 8 * -1)
    )

    canvas.create_text(
        447.0,
        329.0,
        anchor="nw",
        text="isi:",
        fill="#000000",
        font=("Inter Bold", 8 * -1)
    )

    canvas.create_text(
        570.0,
        131.0,
        anchor="nw",
        text="tulis perhitungan :",
        fill="#000000",
        font=("Inter Bold", 8 * -1)
    )

    canvas.create_text(
        23.0,
        465.0,
        anchor="nw",
        text="Voila :",
        fill="#000000",
        font=("Inter Bold", 10 * -1)
    )

    canvas.create_text(
        159.0,
        276.0,
        anchor="nw",
        text="*make sure that u place / write location \nwhere it already set at ( show valid loc )\nto prevent any future error.",
        fill="#FF0000",
        font=("Inter", 10 * -1)
    )

    canvas.create_text(
        561.0,
        191.0,
        anchor="nw",
        text="RANDOM QUOTES",
        fill="#000000",
        font=("JimNightshade Regular", 24 * -1)
    )

    canvas.create_rectangle(
        560.0,
        190.0,
        839.0,
        309.0,
        fill="#D9D9D9",
        outline="")


    def debug():
        data = [entry_1 , entry_2 , entry_3 , entry_4 , entry_5 , entry_6 , entry_7 , entry_8 , entry_9 , entry_10 , entry_11 , entry_12]
        for i , d  in enumerate(data, start=1):
            print(f'{i} - {d.get()}')
        


    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command= debug,
        relief="flat"
    )
    button_2.place(
        x=786.0,
        y=142.0,
        width=43.0,
        height=41.0
    )

    canvas.create_text(
        795.9999718563797,
        152.0,
        anchor="nw",
        text=":)",
        fill="#FFFFFF",
        font=("Inter Bold", 20 * -1)
    )
    # Global variables for Combobox
    sessions = ["SO 1", "SO 2"]
    default_value = StringVar(value="SO 2")
    

    # Functions to handle Combobox behavior
    def on_session_select(event ,combobox):
        selected = default_value.get()
        combobox.configure(values=[selected])

    def reset_session(combobox):
        default_value.set("SO 2")
        combobox.configure(values=sessions)

    style = Style() 
    style.configure( "warnaopsi.TCombobox", background="#f1f2e0", foreground="#000000", borderwidth=2, relief="flat" )
    session_combobox = Combobox( window, textvariable=default_value, values=sessions, style="warnaopsi.TCombobox", state="readonly" )
    session_combobox.place(x=50, y=200, width=80, height=30)
    session_combobox.bind("<<ComboboxSelected>>", lambda event: on_session_select(event, session_combobox))
    reset_button = Button( window, text="Reset Session", command= lambda : reset_session(session_combobox), bg="#D9D9D9", fg="#000716", relief="flat" )
    reset_button.place(x=50, y=250, width=70, height=25 , anchor='nw')

    window.resizable(False, False)
    '''
    entry : 

    1 - sku
    2 - quant
    3 - tambahan
    4 - koli 1
    5 - koli 2
    6 - upload
    7 - keterangan
    8 - result
    9 - location
    10 - isi 1
    11 - isi 2
    12 - calcu

    
    '''
    RECAP_ENTRY : dict[str,Any] = {
        "sku" : entry_1 , 
        "qty" : entry_2 , 
        "additions": entry_3 , 
        "kolian_1": entry_4 , 
        "kolian_2": entry_5 , 
        'upload': entry_6 , 
        'keterangan': entry_7 , 
        'output': entry_8 , 
        'location': entry_9 , 
        'isian_1': entry_10 , 
        'isian_2': entry_11 , 
        'calculator': entry_12 ,
        'sessions': session_combobox
    }

    '''
    button :

    button 1 = browse
    button 2 = calculate
    button 3 = add
    button 4 = hijau pojok kanan (kiri bawah)
    button 5 = export
    button 6 = kuning
    button 7 = hijau sebelah kuning
    button 8 = hijau pojok kanan (kanan tengah)
    button 9 = hijau pojok kanan (kanan atas)
    button 10 = hijau pojok kanan (kiri tengah)
    button 11 = hijau pojok kanan (kiri atas)
    button 12 = show valid loc
    button 13 = clear
    '''
    RECAP_BUTTON :dict[str,Any] = {
        'browse':button_1 ,
        'calculate':button_2,
        'add':button_3,
        'export':button_5,
        

    }

    window.mainloop()

main_UI()